### ISSUE TITLE
why can't I use /

### ISSUE THREAD

**Issue by celevra** [sol1/backupninja#1]
Hi,

i want to backup the whole system an i get following error:
```
Fatal: Sorry, you cannot use 'include = /'
```
regards

Celevra

**Comment by davekempe** [comment]
gday. / is included by default. If you want to backup everything just don't use an include statement.
You can see more output with backupninja -d -n

**Comment by celevra** [comment]
Oh, thats easy, thank you very much
________________________________
Von: Dave Kempe <notifications@github.com>
Gesendet: Samstag, 3. Oktober 2020 09:45
An: sol1/backupninja
Cc: Philipp Zeitschel; Author
Betreff: Re: [sol1/backupninja] why can't I use / (#1)


gday. / is included by default. If you want to backup everything just don't use an include statement.
You can see more output with backupninja -d -n
